name: LinDB Go Client CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-with-coverage:
    name: Uint Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
        id: go
      - name: Make Mock files
        run: make gomock
      - name: Test
        run: make test
      - name: Upload
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
